# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfTriage < Formula
  desc "An AI-powered semantic plan analyzer for Terraform and OpenTofu."
  homepage "https://github.com/balmha/tf-triage"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balmha/tf-triage/releases/download/v0.1.0/tf-triage_darwin_amd64.tar.gz"
      sha256 "07fcd1c5e4e53adfd100335fa7e30833ad154e224ff0770df7c54818c0ab1108"

      define_method(:install) do
        bin.install "tf-triage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balmha/tf-triage/releases/download/v0.1.0/tf-triage_darwin_arm64.tar.gz"
      sha256 "88bd9bd483f6b8e13a592ffd47c09bbd02042ca8e8a4273454fcf9d52f155cbc"

      define_method(:install) do
        bin.install "tf-triage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balmha/tf-triage/releases/download/v0.1.0/tf-triage_linux_amd64.tar.gz"
      sha256 "8adcfdfed1c53d40f1f796fba0fd15597c01ece7f622a4faf0df3084046a002b"
      define_method(:install) do
        bin.install "tf-triage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balmha/tf-triage/releases/download/v0.1.0/tf-triage_linux_arm64.tar.gz"
      sha256 "678e74a20c44a832a06b66d62c283452663169ce9f093b9aa343da09f53f613a"
      define_method(:install) do
        bin.install "tf-triage"
      end
    end
  end

  test do
    system "#{bin}/tf-triage --version"
  end
end
