# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfTriage < Formula
  desc "An AI-powered semantic plan analyzer for Terraform and OpenTofu."
  homepage "https://github.com/balmha/tf-triage"
  version "0.2.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balmha/tf-triage/releases/download/v0.2.0/tf-triage_darwin_amd64.tar.gz"
      sha256 "5a9cb6c09727f206252193bf6eebf1b81974ac75afe080abfafed43d8e9807b7"

      define_method(:install) do
        bin.install "tf-triage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balmha/tf-triage/releases/download/v0.2.0/tf-triage_darwin_arm64.tar.gz"
      sha256 "20977966ca1938fe8658c94a731766eb2b889683161396248b1b0de193ed679b"

      define_method(:install) do
        bin.install "tf-triage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balmha/tf-triage/releases/download/v0.2.0/tf-triage_linux_amd64.tar.gz"
      sha256 "0bd971f2d09e27d20e885688ab07b2a4536f1b887b592d743019670e4143924b"
      define_method(:install) do
        bin.install "tf-triage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balmha/tf-triage/releases/download/v0.2.0/tf-triage_linux_arm64.tar.gz"
      sha256 "98126deedb21fee0126159f8ad0be24960e0f99fdcc6b59b5fbee89633c086c0"
      define_method(:install) do
        bin.install "tf-triage"
      end
    end
  end

  test do
    system "#{bin}/tf-triage --version"
  end
end
