# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfTriage < Formula
  desc "An AI-powered semantic plan analyzer for Terraform and OpenTofu."
  homepage "https://github.com/balmha/tf-triage"
  version "0.3.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balmha/tf-triage/releases/download/v0.3.0/tf-triage_darwin_amd64.tar.gz"
      sha256 "ac45f77a1c6847419d14fd18bb3a76e36fe37c11d591442cd7420f5456a0e3ef"

      define_method(:install) do
        bin.install "tf-triage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balmha/tf-triage/releases/download/v0.3.0/tf-triage_darwin_arm64.tar.gz"
      sha256 "96a8455d0af97d792b39d914b5cae206201dae4641f9a41c1205dc665b4397ab"

      define_method(:install) do
        bin.install "tf-triage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balmha/tf-triage/releases/download/v0.3.0/tf-triage_linux_amd64.tar.gz"
      sha256 "871460eff4cb79671ddf895347593b97b9aaf7bfc1bbecf2f0f901416a8ee5b6"
      define_method(:install) do
        bin.install "tf-triage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balmha/tf-triage/releases/download/v0.3.0/tf-triage_linux_arm64.tar.gz"
      sha256 "647cc7dff2c3431475f19a5b50f683c565cd8a55e0cd321497056e792f4a2bfa"
      define_method(:install) do
        bin.install "tf-triage"
      end
    end
  end

  test do
    system "#{bin}/tf-triage --version"
  end
end
